"""Add missing day 3 fields

Revision ID: 7fed6b8c9e2f
Revises: aaca4bb74a7c
Create Date: 2026-07-29 12:47:54.249926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fed6b8c9e2f'
down_revision: Union[str, Sequence[str], None] = 'aaca4bb74a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('complaints', sa.Column('image_url', sa.String(), nullable=False))
    op.add_column('complaints', sa.Column('severity_score', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('severity_level', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('upvote_count', sa.Integer(), nullable=True))
    op.alter_column('complaints', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('complaints', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('complaints', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('complaints', 'upvote_count')
    op.drop_column('complaints', 'severity_level')
    op.drop_column('complaints', 'severity_score')
    op.drop_column('complaints', 'image_url')
    op.drop_column('complaints', 'user_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
